stages:
  #- build
  - tests

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build
  cache:
    paths:
      - ./node_modules
  artifacts:
    expire_in: 1 hour
    paths:
      - ./dist/hello-world
  only:
    - master

tests:
  stage: tests
  image: circleci/node:14-browsers
  script:
    - npm install
    - npm install -g @angular/cli
    - ng test
  cache:
    paths:
      - ./node_modules
  only:
    - master
